[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
itertools = "0.10.5"
variadic_generics = "0.1.2"
sepax2d = "0.3.8"
notan = {version = "0.9.5", features = ["egui"]}
glob = "0.3.1"
pathfinding = "4.3.0"
anyhow = "1.0.71"
broccoli = "6.2.2"
